- name: Set up GPU facts
  ansible.builtin.set_fact:
    nvidia: false
    amd: false
    intel: false

- name: Check GPU type
  ansible.builtin.shell: lspci | grep -E "(VGA|3D)"
  register: lspci_output

- name: Include appropriate role
  block:
    - block:
        - name: Set nvidia fact to true
          ansible.builtin.set_fact: nvidia=true
        - name: Include NVIDIA GPU graphics setup
          ansible.builtin.include_tasks: nvidia.yml
      when: '"nvidia" in lspci_output.stdout|lower'
    - block:
        - name: Set intel fact to true
          ansible.builtin.set_fact: intel=true
        - name: Include Intel graphics setup
          ansible.builtin.include_tasks: intel.yml
      when: '"intel" in lspci_output.stdout|lower'
    - block:
        - name: Set amd fact to true
          ansible.builtin.set_fact: amd=true
        - name: Include AMD GPU graphics setup
          ansible.builtin.include_tasks: amd.yml
      when: '"advanced micro devices" in lspci_output.stdout|lower'

