- name: Set up GPU facts
  ansible.builtin.set_fact:
    nvidia: false
    amd: false
    intel: false

- name: Check GPU type
  ansible.builtin.shell: |
    set -o pipefail
    lspci | grep -E "(VGA|3D)"
  register: lspci_output
  changed_when: false

- name: Set up NVIDIA graphics
  when: '"nvidia" in lspci_output.stdout|lower'
  block:
    - name: Set nvidia fact to true
      ansible.builtin.set_fact:
        nvidia: true
    - name: Include NVIDIA GPU graphics setup
      ansible.builtin.include_tasks: nvidia.yml

- name: Set up Intel graphics
  when: '"intel" in lspci_output.stdout|lower'
  block:
    - name: Set intel fact to true
      ansible.builtin.set_fact:
        intel: true
    - name: Include Intel graphics setup
      ansible.builtin.include_tasks: intel.yml

- name: Set up AMD graphics
  when: '"advanced micro devices" in lspci_output.stdout|lower'
  block:
    - name: Set amd fact to true
      ansible.builtin.set_fact:
        amd: true
    - name: Include AMD GPU graphics setup
      ansible.builtin.include_tasks: amd.yml
