- name: Install rustup
  community.general.pacman:
    name: rustup
    state: present

- name: Set default rust version for aur_builder
  ansible.builtin.command: rustup default stable
  become: true
  become_user: aur_builder
  register: rustup_out
  changed_when: '"installed" in rustup_out.stdout_lines[-1]'

- name: Install paru from AUR
  kewlfft.aur.aur:
    name: paru
    use: makepkg
    state: present
  become: true
  become_user: aur_builder

- name: Install informant from AUR with paru
  kewlfft.aur.aur:
    name: informant
    state: present
    use: paru
  become: true
  become_user: aur_builder

- name: Add admin to informant group
  ansible.builtin.user:
    name: admin
    groups: ["informant"]
    append: true

- name: Read informant messages
  ansible.builtin.command: informant read --all
  register: informant_output
  changed_when: informant_output.rc == 0

- name: Enable multilib repository
  ansible.builtin.replace:
    path: /etc/pacman.conf
    regexp: '(?m)^#(\[multilib\])$\n#(Include = \/etc\/pacman\.d\/mirrorlist)$'
    replace: '\1\n\2'
  when: use_lib32|bool

- name: Update package cache
  community.general.pacman:
    update_cache: true
