- name: Install frequently used packages
  block:
    - name: Install packages from official repos
      community.general.pacman:
        name:
          - neovim
          - thunderbird
          - mpv
          - pipewire
          - wireplumber
          - pipewire-audio
          - torbrowser-launcher
          - ufw
        state: present
    - name: Install packages from AUR
      kewlfft.aur.aur:
        name:
          - webcord
          - anki-bin
          - arkenfox-user.js
          - mullvad-browser-bin
        use: paru
        state: present
      become: true
      become_user: aur_builder
    - name: Install 32-bit packages
      community.general.pacman:
        name:
          - lib32-pipewire
        state: present
        update_cache: true
      when: use_lib32|bool

- name: Set up AstroNvim config
  ansible.builtin.shell: sudo -u user git clone https://github.com/soravoid/astronvim-user-config.git /home/user/.config/nvim
  args:
    creates: /home/user/.config/nvim

- name: Set up UFW
  block:
    - name: Set UFW to default deny all incoming traffic
      ansible.builtin.shell: ufw default deny
    - name: Enable UFW firewall
      ansible.builtin.shell: ufw --force enable
    - name: Enable UFW systemd service
      ansible.builtin.systemd_service:
        name: ufw
        enabled: true
