- name: Install frequently used packages
  block:
    - name: Install packages from official repos
      community.general.pacman:
        name:
          - neovim
          - thunderbird
          - mpv
          - pipewire
          - wireplumber
          - pipewire-audio
          - torbrowser-launcher
          - ufw
        state: present
        update_cache: true
    - name: Install packages from AUR
      kewlfft.aur.aur:
        name:
          - webcord
          - anki-bin
          - arkenfox-user.js
          - mullvad-browser-bin
        use: paru
        state: present
      become: true
      become_user: aur_builder
    - name: Install 32-bit packages
      community.general.pacman:
        name:
          - lib32-pipewire
        state: present
        update_cache: true
      when: use_lib32|bool

- name: Set up AstroNvim config
  ansible.builtin.command: sudo -u user git clone https://github.com/soravoid/astronvim-user-config.git /home/user/.config/nvim
  args:
    creates: /home/user/.config/nvim

- name: Set up UFW
  block:
    - name: Set UFW to default deny all incoming traffic
      ansible.builtin.command: ufw default deny
      register: ufw_deny_out
      changed_when: ufw_deny_out.rc == 0
    - name: Enable UFW firewall
      ansible.builtin.command: ufw --force enable
      register: ufw_enable_out
      changed_when: ufw_enable_out.rc == 0
    - name: Enable UFW systemd service
      ansible.builtin.systemd_service:
        name: ufw
        enabled: true

- name: Set default rust version for user
  ansible.builtin.command: rustup default stable
  become: true
  become_user: user
  register: rustup_out
  changed_when: '"installed" in rustup_out.stdout_lines[-1]'

- name: Allow admin account to use sudo
  ansible.builtin.copy:
    dest: /etc/sudoers.d/admin.conf
    content: 'admin ALL=(ALL) ALL'
    owner: root
    group: root
    mode: '0644'
