- name: Install frequently used packages
  block:
    - name: Install packages from official repos
      community.general.pacman:
        name:
          - firefox
          - neovim
          - kitty
          - thunderbird
          - mpv
          - pipewire
          - wireplumber
          - pipewire-audio
        state: present
    - name: Install paru from AUR
      kewlfft.aur.aur:
        name: paru
        use: makepkg
        state: present
    - name: Install packages from AUR
      kewlfft.aur.aur:
        name:
          - webcord
          - anki
          - informant
        use: paru
        state: present

- name: Enable pipewire service
  ansible.builtin.systemd_service:
    name: pipewire
    enabled: true

- name: Enable multilib repository
  ansible.builtin.replace:
    path: /etc/pacman.conf
    regexp: '(?m)^#(\[multilib\])$\n#(Include = \/etc\/pacman\.d\/mirrorlist)$'
    replace: '\1\n\2'
  when: use_lib32|bool

- name: Install 32-bit packages
  community.general.pacman:
    name:
      - lib32-pipewire
    state: present
  when: use_lib32|bool

- name: Set up AstroNvim config
  ansible.builtin.git:
    repo: https://github.com/soravoid/astronvim-user-config.git
    separate_git_dir: /home/user/.config/nvim
