- name: Install frequently used packages
  block:
    - name: Install packages from official repos
      community.general.pacman:
        name:
          - firefox
          - neovim
          - kitty
          - thunderbird
          - mpv
          - pipewire
          - wireplumber
          - pipewire-audio
        state: present
    - name: Install paru from AUR
      kewlfft.aur.aur:
        name: paru
        use: makepkg
        state: present
      become: yes
      become_user: aur_builder
    - name: Install packages from AUR
      kewlfft.aur.aur:
        name:
          - webcord
          - anki-bin
          - informant
        use: paru
        state: present
      become: yes
      become_user: aur_builder

- name: Read informant messages
  ansible.builtin.shell: informant read --all

- name: Enable multilib repository
  ansible.builtin.replace:
    path: /etc/pacman.conf
    regexp: '(?m)^#(\[multilib\])$\n#(Include = \/etc\/pacman\.d\/mirrorlist)$'
    replace: '\1\n\2'
  when: use_lib32|bool

- name: Install 32-bit packages
  community.general.pacman:
    name:
      - lib32-pipewire
    state: present
    update_cache: true
  when: use_lib32|bool

- name: Create .config directory
  ansible.builtin.shell: mkdir -p /home/user/.config/nvim

- name: Set up AstroNvim config
  ansible.builtin.git:
    repo: https://github.com/soravoid/astronvim-user-config.git
    dest: /home/user/.config/nvim
