- name: Install frequently used packages
  block:
    - name: Installing packages from official repos
      community.general.pacman:
        name:
          - firefox
          - neovim
          - kitty
          - thunderbird
          - mpv
        state: present
    - name: Installing packages from AUR
      kewlfft.aur.aur:
        name:
          - webcord
          - anki
        state: present

- name: Set up AstroNvim config
  ansible.builtin.git:
    repo: gitea@git.jaden.rs:suusuu/astronvim-user-config.git
    separate_git_dir: /home/user/.config/nvim
