- name: Clone git repo for {{ item }}  # noqa: latest
  ansible.builtin.git:
    repo: 'https://aur.archlinux.org/{{ item }}.git'
    dest: '/home/aur_builder/{{ item }}'
  become: true
  become_user: aur_builder

- name: Receive GPG keys
  ansible.builtin.command: >
    ./recv_gpg_keys.sh /home/aur_builder/{{ item }}
  become: true
  become_user: aur_builder
  args:
    chdir: assets
  register: gpg_out
  changed_when: gpg_out.rc == 0

- name: Find package files in repo for {{ item }}
  ansible.builtin.find:
    path: '/home/aur_builder/{{ item }}'
    patterns:
      - '*.pkg.tar.xz'
      - '*.pkg.tar.zstd'
      - '*.pkg.tar.xz.sig'
      - '*.pkg.tar.zstd.sig'
  register: git_files

- name: 'Delete .pkg.tar.{xz,zstd}{,.sig}'
  ansible.builtin.file:
    path: '{{ file_item }}'
    state: absent
  loop: '{{ git_files.files }}'
  loop_control:
    loop_var: file_item

- name: Building {{ item }}
  ansible.builtin.shell: >
    makepkg -s -C --noconfirm{% if item == 'systemd-selinux' %} --no-check{% endif %}
  args:
    chdir: '/home/aur_builder/{{ item }}'
    creates: '/home/aur_builder/{{ item + "/*" + makepkg_ext.stdout }}'
  become: true
  become_user: aur_builder

- name: Installing {{ item }}
  ansible.builtin.command: >
      pacman -U --ask=4 {{ q('ansible.builtin.fileglob', '/home/aur_builder/' + item + '/' + '*' + makepkg_ext.stdout) | first | trim }}
  register: pacman_out
  changed_when: pacman_out.rc == 0

- name: Cleaning up build files for {{ item }}
  ansible.builtin.file:
    path: /home/aur_builder/{{ item }}
    state: absent
