- name: Prevent user 'aur_builder' from using sudo
  ansible.builtin.file:
    path: /etc/sudoers.d/11-install-aur_builder
    state: absent

- name: Kill all processes belonging to aur_builder
  ansible.builtin.command: pkill -u aur_builder
  register: pkill_output
  changed_when: pkill_output.rc == 0

- name: Delete 'aur_builder' user
  ansible.builtin.user:
    name: aur_builder
    state: absent
    remove: true
