- name: Install mold linker
  community.general.pacman:
    name: mold
    state: present

- name: Set more performant compilation flags
  block:
    - name: Change CFLAGS
      ansible.builtin.lineinfile:
        path: /etc/makepkg.conf
        regexp: '^CFLAGS="-march=.*? (.*)$'
        backrefs: true
        line: 'CFLAGS="-march=native \1'
    - name: Change LDFLAGS
      ansible.builtin.lineinfile:
        path: /etc/makepkg.conf
        regexp: '^LDFLAGS="(.*)$'
        backrefs: true
        line: 'LDFLAGS="-fuse-ld=mold \1'
    - name: Change RUSTFLAGS
      ansible.builtin.lineinfile:
        path: /etc/makepkg.conf
        regexp: '^RUSTFLAGS="(.*)$'
        backrefs: true
        line: 'RUSTFLAGS="-C target-cpu=native -C link-arg=-fuse-ld=mold \1'
