- name: Install hyprland packages
  community.general.pacman:
    name:
      - hyprland
      - xdg-desktop-portal-hyprland
      - mako
      - polkit-kde-agent
      - qt5-wayland
      - qt6-wayland
      - swww
      - hypridle
      - hyprlock
      - hyprcursor
      - dolphin
    state: present

- name: Install hyprland AUR packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - nordzy-cursors-hyprcursor
      - anyrun-git
    state: present
    use: paru

- name: Ensure hyprland config directory exists
  ansible.builtin.shell: sudo -u user mkdir -p /home/user/.config/hypr

- name: Copy hyprland config file
  ansible.builtin.copy:
    src: assets/hyprland.conf
    dest: /home/user/.config/hypr/hyprland.conf
    owner: user
    group: user
    mode: '0644'

- name: Copy anyrun config files
  ansible.builtin.copy:
    src: /etc/anyrun/
    dest: /home/user/.config/anyrun/
    owner: user
    group: user

- name: Set up NVIDIA for Hyprland
  when: nvidia
  block:
    - name: Install required packages
      community.general.pacman:
        name: egl-wayland
        state: present
    - name: Move environment variables to hyprland.conf
      ansible.builtin.shell: ./hyprland_envvars.py /home/user
      args:
        chdir: assets
    - name: Add cursor block to hyprland.conf
      ansible.builtin.blockinfile:
        block: |
          cursor {
              no_hardware_cursors = true
          }
        path: /home/user/.config/hypr/hyprland.conf
        create: no

