- name: Install firefox
  community.general.pacman:
    name: firefox
    state: present

- name: Create 'default' firefox profile
  ansible.builtin.command: sudo -u user firefox --headless -CreateProfile default
  register: firefox_profile_out
  args:
    creates: /home/user/.mozilla/firefox/*.default

- name: Find firefox profile folder
  ansible.builtin.shell: >
    set -o pipefail |
    ls -ld /home/user/.mozilla/firefox/*.default | awk '{print $9}'
  changed_when: false
  register: firefox_profile
  failed_when: firefox_profile.rc != 0 or firefox_profile.stdout|trim == ''

- name: Copy user.js to profile folder
  ansible.builtin.copy:
    src: /usr/share/arkenfox-user.js/user.js
    dest: '{{ firefox_profile.stdout }}/user.js'
    owner: user
    group: user
    mode: '0644'

- name: Copy user-overrides.js to profile folder
  ansible.builtin.copy:
    src: assets/user-overrides.js
    dest: '{{ firefox_profile.stdout }}/user-overrides.js'
    owner: user
    group: user
    mode: '0644'

- name: Update profile with arkenfox scripts
  ansible.builtin.command: sudo -u user arkenfox-updater -sp {{ firefox_profile.stdout }}
  args:
    chdir: '{{ firefox_profile.stdout }}'
  register: arkenfox_out
  changed_when: arkenfox_out.rc == 0

- name: Copy firefox profiles.ini
  ansible.builtin.template:
    src: assets/firefox_profile.stdout_ini
    dest: /home/user/.mozilla/firefox/profiles.ini
    owner: user
    group: user
    mode: '0644'

- name: Delete firefox telemetry libraries
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  with_items:
    - /usr/lib/firefox/crashreporter
    - /usr/lib/firefox/minidump-analyzer
    - /usr/lib/firefox/pingsender
